// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';

export function CreateCamera(arg1:api.CreateCameraRequest):Promise<api.CameraDTO>;

export function DeleteCamera(arg1:string):Promise<void>;

export function DiscoverONVIFCameras():Promise<Array<api.DiscoveredCamera>>;

export function GetCamera(arg1:string):Promise<api.CameraDTO>;

export function GetCameraPresets(arg1:string):Promise<Array<api.PresetDTO>>;

export function GetONVIFProfiles(arg1:api.GetProfilesRequest):Promise<Array<api.ProfileDTO>>;

export function GetONVIFStreamURI(arg1:api.GetStreamURIRequest):Promise<string>;

export function ListCameras():Promise<Array<api.CameraDTO>>;

export function ReorderCameras(arg1:Array<string>):Promise<void>;

export function TestDirectStream(arg1:api.TestDirectStreamRequest):Promise<api.TestDirectStreamResponse>;

export function TestONVIFCamera(arg1:api.TestONVIFRequest):Promise<api.TestONVIFResponse>;

export function UpdateCamera(arg1:string,arg2:api.UpdateCameraRequest):Promise<api.CameraDTO>;
