// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCamera(arg1) {
  return window['go']['api']['CameraService']['CreateCamera'](arg1);
}

export function DeleteCamera(arg1) {
  return window['go']['api']['CameraService']['DeleteCamera'](arg1);
}

export function DiscoverONVIFCameras() {
  return window['go']['api']['CameraService']['DiscoverONVIFCameras']();
}

export function GetCamera(arg1) {
  return window['go']['api']['CameraService']['GetCamera'](arg1);
}

export function GetONVIFProfiles(arg1) {
  return window['go']['api']['CameraService']['GetONVIFProfiles'](arg1);
}

export function GetONVIFStreamURI(arg1) {
  return window['go']['api']['CameraService']['GetONVIFStreamURI'](arg1);
}

export function ListCameras() {
  return window['go']['api']['CameraService']['ListCameras']();
}

export function ReorderCameras(arg1) {
  return window['go']['api']['CameraService']['ReorderCameras'](arg1);
}

export function TestDirectStream(arg1) {
  return window['go']['api']['CameraService']['TestDirectStream'](arg1);
}

export function TestONVIFCamera(arg1) {
  return window['go']['api']['CameraService']['TestONVIFCamera'](arg1);
}

export function UpdateCamera(arg1, arg2) {
  return window['go']['api']['CameraService']['UpdateCamera'](arg1, arg2);
}
