// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {stream} from '../models';
import {ws} from '../models';

export function GetStreamStatus(arg1:string):Promise<api.StreamStatus>;

export function Hub():Promise<stream.Hub>;

export function PTZ(arg1:string,arg2:ws.PTZCommand):Promise<void>;

export function Start(arg1:string):Promise<void>;

export function StartAll():Promise<void>;

export function StartAllStreams():Promise<void>;

export function StartStream(arg1:string):Promise<void>;

export function Stop(arg1:string):Promise<void>;

export function StopAll():Promise<void>;

export function StopAllStreams():Promise<void>;

export function StopStream(arg1:string):Promise<void>;

export function StreamURL(arg1:string):Promise<string>;

export function Subscribe(arg1:string):Promise<any>;
