// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStreamStatus(arg1) {
  return window['go']['api']['StreamService']['GetStreamStatus'](arg1);
}

export function Hub() {
  return window['go']['api']['StreamService']['Hub']();
}

export function PTZ(arg1, arg2) {
  return window['go']['api']['StreamService']['PTZ'](arg1, arg2);
}

export function Start(arg1) {
  return window['go']['api']['StreamService']['Start'](arg1);
}

export function StartAll() {
  return window['go']['api']['StreamService']['StartAll']();
}

export function StartAllStreams() {
  return window['go']['api']['StreamService']['StartAllStreams']();
}

export function StartStream(arg1) {
  return window['go']['api']['StreamService']['StartStream'](arg1);
}

export function Stop(arg1) {
  return window['go']['api']['StreamService']['Stop'](arg1);
}

export function StopAll() {
  return window['go']['api']['StreamService']['StopAll']();
}

export function StopAllStreams() {
  return window['go']['api']['StreamService']['StopAllStreams']();
}

export function StopStream(arg1) {
  return window['go']['api']['StreamService']['StopStream'](arg1);
}

export function StreamURL(arg1) {
  return window['go']['api']['StreamService']['StreamURL'](arg1);
}

export function Subscribe(arg1) {
  return window['go']['api']['StreamService']['Subscribe'](arg1);
}
